version: "3.2"
services:

  db:
    container_name: PostgresDB
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - /usr/local/pg_data:/var/lib/postgresql/data
    ports: # dev
      - "${PGPORT}:${PGPORT}"

  server:
    container_name: GophKeeper
    restart: unless-stopped
    build:
      context: .
    env_file:
      - prod.env
      - final.env
    ports:
      - "9999:9999"