// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: backend.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GophKeeperClient is the client API for GophKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophKeeperClient interface {
	Ping(ctx context.Context, in *Empty_DTO, opts ...grpc.CallOption) (*Empty_DTO, error)
	Login(ctx context.Context, in *LoginPassPair, opts ...grpc.CallOption) (*SessionID_DTO, error)
	KickOtherSession(ctx context.Context, in *LoginPassPair, opts ...grpc.CallOption) (*SessionID_DTO, error)
	Register(ctx context.Context, in *LoginPassPair, opts ...grpc.CallOption) (*SessionID_DTO, error)
	StoreLoginPassword(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error)
	LoadLoginPassword(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error)
}

type gophKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGophKeeperClient(cc grpc.ClientConnInterface) GophKeeperClient {
	return &gophKeeperClient{cc}
}

func (c *gophKeeperClient) Ping(ctx context.Context, in *Empty_DTO, opts ...grpc.CallOption) (*Empty_DTO, error) {
	out := new(Empty_DTO)
	err := c.cc.Invoke(ctx, "/internal.server.pb.GophKeeper/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) Login(ctx context.Context, in *LoginPassPair, opts ...grpc.CallOption) (*SessionID_DTO, error) {
	out := new(SessionID_DTO)
	err := c.cc.Invoke(ctx, "/internal.server.pb.GophKeeper/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) KickOtherSession(ctx context.Context, in *LoginPassPair, opts ...grpc.CallOption) (*SessionID_DTO, error) {
	out := new(SessionID_DTO)
	err := c.cc.Invoke(ctx, "/internal.server.pb.GophKeeper/KickOtherSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) Register(ctx context.Context, in *LoginPassPair, opts ...grpc.CallOption) (*SessionID_DTO, error) {
	out := new(SessionID_DTO)
	err := c.cc.Invoke(ctx, "/internal.server.pb.GophKeeper/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) StoreLoginPassword(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error) {
	out := new(DataID_DTO)
	err := c.cc.Invoke(ctx, "/internal.server.pb.GophKeeper/StoreLoginPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) LoadLoginPassword(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error) {
	out := new(SecureData_DTO)
	err := c.cc.Invoke(ctx, "/internal.server.pb.GophKeeper/LoadLoginPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GophKeeperServer is the server API for GophKeeper service.
// All implementations must embed UnimplementedGophKeeperServer
// for forward compatibility
type GophKeeperServer interface {
	Ping(context.Context, *Empty_DTO) (*Empty_DTO, error)
	Login(context.Context, *LoginPassPair) (*SessionID_DTO, error)
	KickOtherSession(context.Context, *LoginPassPair) (*SessionID_DTO, error)
	Register(context.Context, *LoginPassPair) (*SessionID_DTO, error)
	StoreLoginPassword(context.Context, *SecureData_DTO) (*DataID_DTO, error)
	LoadLoginPassword(context.Context, *DataID_DTO) (*SecureData_DTO, error)
	mustEmbedUnimplementedGophKeeperServer()
}

// UnimplementedGophKeeperServer must be embedded to have forward compatible implementations.
type UnimplementedGophKeeperServer struct {
}

func (UnimplementedGophKeeperServer) Ping(context.Context, *Empty_DTO) (*Empty_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGophKeeperServer) Login(context.Context, *LoginPassPair) (*SessionID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGophKeeperServer) KickOtherSession(context.Context, *LoginPassPair) (*SessionID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickOtherSession not implemented")
}
func (UnimplementedGophKeeperServer) Register(context.Context, *LoginPassPair) (*SessionID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGophKeeperServer) StoreLoginPassword(context.Context, *SecureData_DTO) (*DataID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreLoginPassword not implemented")
}
func (UnimplementedGophKeeperServer) LoadLoginPassword(context.Context, *DataID_DTO) (*SecureData_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadLoginPassword not implemented")
}
func (UnimplementedGophKeeperServer) mustEmbedUnimplementedGophKeeperServer() {}

// UnsafeGophKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophKeeperServer will
// result in compilation errors.
type UnsafeGophKeeperServer interface {
	mustEmbedUnimplementedGophKeeperServer()
}

func RegisterGophKeeperServer(s grpc.ServiceRegistrar, srv GophKeeperServer) {
	s.RegisterService(&GophKeeper_ServiceDesc, srv)
}

func _GophKeeper_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.server.pb.GophKeeper/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).Ping(ctx, req.(*Empty_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPassPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.server.pb.GophKeeper/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).Login(ctx, req.(*LoginPassPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_KickOtherSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPassPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).KickOtherSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.server.pb.GophKeeper/KickOtherSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).KickOtherSession(ctx, req.(*LoginPassPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPassPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.server.pb.GophKeeper/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).Register(ctx, req.(*LoginPassPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_StoreLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureData_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).StoreLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.server.pb.GophKeeper/StoreLoginPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).StoreLoginPassword(ctx, req.(*SecureData_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_LoadLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataID_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).LoadLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.server.pb.GophKeeper/LoadLoginPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).LoadLoginPassword(ctx, req.(*DataID_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

// GophKeeper_ServiceDesc is the grpc.ServiceDesc for GophKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GophKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.server.pb.GophKeeper",
	HandlerType: (*GophKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GophKeeper_Ping_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GophKeeper_Login_Handler,
		},
		{
			MethodName: "KickOtherSession",
			Handler:    _GophKeeper_KickOtherSession_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GophKeeper_Register_Handler,
		},
		{
			MethodName: "StoreLoginPassword",
			Handler:    _GophKeeper_StoreLoginPassword_Handler,
		},
		{
			MethodName: "LoadLoginPassword",
			Handler:    _GophKeeper_LoadLoginPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
