// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: backend.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GophKeeperClient is the client API for GophKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophKeeperClient interface {
	GetCategoryHead(ctx context.Context, in *CategoryType_DTO, opts ...grpc.CallOption) (*CategoryHead_DTO, error)
	StoreCredData(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error)
	LoadCredData(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error)
	StoreTextData(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error)
	LoadTextData(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error)
	StoreCardData(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error)
	LoadCardData(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error)
	StoreFile(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error)
	LoadFile(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error)
}

type gophKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGophKeeperClient(cc grpc.ClientConnInterface) GophKeeperClient {
	return &gophKeeperClient{cc}
}

func (c *gophKeeperClient) GetCategoryHead(ctx context.Context, in *CategoryType_DTO, opts ...grpc.CallOption) (*CategoryHead_DTO, error) {
	out := new(CategoryHead_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/GetCategoryHead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) StoreCredData(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error) {
	out := new(DataID_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/StoreCredData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) LoadCredData(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error) {
	out := new(SecureData_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/LoadCredData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) StoreTextData(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error) {
	out := new(DataID_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/StoreTextData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) LoadTextData(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error) {
	out := new(SecureData_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/LoadTextData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) StoreCardData(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error) {
	out := new(DataID_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/StoreCardData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) LoadCardData(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error) {
	out := new(SecureData_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/LoadCardData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) StoreFile(ctx context.Context, in *SecureData_DTO, opts ...grpc.CallOption) (*DataID_DTO, error) {
	out := new(DataID_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/StoreFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeeperClient) LoadFile(ctx context.Context, in *DataID_DTO, opts ...grpc.CallOption) (*SecureData_DTO, error) {
	out := new(SecureData_DTO)
	err := c.cc.Invoke(ctx, "/base.GophKeeper/LoadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GophKeeperServer is the server API for GophKeeper service.
// All implementations must embed UnimplementedGophKeeperServer
// for forward compatibility
type GophKeeperServer interface {
	GetCategoryHead(context.Context, *CategoryType_DTO) (*CategoryHead_DTO, error)
	StoreCredData(context.Context, *SecureData_DTO) (*DataID_DTO, error)
	LoadCredData(context.Context, *DataID_DTO) (*SecureData_DTO, error)
	StoreTextData(context.Context, *SecureData_DTO) (*DataID_DTO, error)
	LoadTextData(context.Context, *DataID_DTO) (*SecureData_DTO, error)
	StoreCardData(context.Context, *SecureData_DTO) (*DataID_DTO, error)
	LoadCardData(context.Context, *DataID_DTO) (*SecureData_DTO, error)
	StoreFile(context.Context, *SecureData_DTO) (*DataID_DTO, error)
	LoadFile(context.Context, *DataID_DTO) (*SecureData_DTO, error)
	mustEmbedUnimplementedGophKeeperServer()
}

// UnimplementedGophKeeperServer must be embedded to have forward compatible implementations.
type UnimplementedGophKeeperServer struct {
}

func (UnimplementedGophKeeperServer) GetCategoryHead(context.Context, *CategoryType_DTO) (*CategoryHead_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryHead not implemented")
}
func (UnimplementedGophKeeperServer) StoreCredData(context.Context, *SecureData_DTO) (*DataID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreCredData not implemented")
}
func (UnimplementedGophKeeperServer) LoadCredData(context.Context, *DataID_DTO) (*SecureData_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadCredData not implemented")
}
func (UnimplementedGophKeeperServer) StoreTextData(context.Context, *SecureData_DTO) (*DataID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreTextData not implemented")
}
func (UnimplementedGophKeeperServer) LoadTextData(context.Context, *DataID_DTO) (*SecureData_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadTextData not implemented")
}
func (UnimplementedGophKeeperServer) StoreCardData(context.Context, *SecureData_DTO) (*DataID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreCardData not implemented")
}
func (UnimplementedGophKeeperServer) LoadCardData(context.Context, *DataID_DTO) (*SecureData_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadCardData not implemented")
}
func (UnimplementedGophKeeperServer) StoreFile(context.Context, *SecureData_DTO) (*DataID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedGophKeeperServer) LoadFile(context.Context, *DataID_DTO) (*SecureData_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadFile not implemented")
}
func (UnimplementedGophKeeperServer) mustEmbedUnimplementedGophKeeperServer() {}

// UnsafeGophKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophKeeperServer will
// result in compilation errors.
type UnsafeGophKeeperServer interface {
	mustEmbedUnimplementedGophKeeperServer()
}

func RegisterGophKeeperServer(s grpc.ServiceRegistrar, srv GophKeeperServer) {
	s.RegisterService(&GophKeeper_ServiceDesc, srv)
}

func _GophKeeper_GetCategoryHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryType_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).GetCategoryHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/GetCategoryHead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).GetCategoryHead(ctx, req.(*CategoryType_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_StoreCredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureData_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).StoreCredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/StoreCredData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).StoreCredData(ctx, req.(*SecureData_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_LoadCredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataID_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).LoadCredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/LoadCredData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).LoadCredData(ctx, req.(*DataID_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_StoreTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureData_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).StoreTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/StoreTextData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).StoreTextData(ctx, req.(*SecureData_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_LoadTextData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataID_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).LoadTextData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/LoadTextData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).LoadTextData(ctx, req.(*DataID_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_StoreCardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureData_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).StoreCardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/StoreCardData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).StoreCardData(ctx, req.(*SecureData_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_LoadCardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataID_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).LoadCardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/LoadCardData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).LoadCardData(ctx, req.(*DataID_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_StoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureData_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).StoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/StoreFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).StoreFile(ctx, req.(*SecureData_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeeper_LoadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataID_DTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeeperServer).LoadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.GophKeeper/LoadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeeperServer).LoadFile(ctx, req.(*DataID_DTO))
	}
	return interceptor(ctx, in, info, handler)
}

// GophKeeper_ServiceDesc is the grpc.ServiceDesc for GophKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GophKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base.GophKeeper",
	HandlerType: (*GophKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategoryHead",
			Handler:    _GophKeeper_GetCategoryHead_Handler,
		},
		{
			MethodName: "StoreCredData",
			Handler:    _GophKeeper_StoreCredData_Handler,
		},
		{
			MethodName: "LoadCredData",
			Handler:    _GophKeeper_LoadCredData_Handler,
		},
		{
			MethodName: "StoreTextData",
			Handler:    _GophKeeper_StoreTextData_Handler,
		},
		{
			MethodName: "LoadTextData",
			Handler:    _GophKeeper_LoadTextData_Handler,
		},
		{
			MethodName: "StoreCardData",
			Handler:    _GophKeeper_StoreCardData_Handler,
		},
		{
			MethodName: "LoadCardData",
			Handler:    _GophKeeper_LoadCardData_Handler,
		},
		{
			MethodName: "StoreFile",
			Handler:    _GophKeeper_StoreFile_Handler,
		},
		{
			MethodName: "LoadFile",
			Handler:    _GophKeeper_LoadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*SessionID_DTO, error)
	KickOtherSession(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*SessionID_DTO, error)
	Register(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Empty, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/base.Auth/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*SessionID_DTO, error) {
	out := new(SessionID_DTO)
	err := c.cc.Invoke(ctx, "/base.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) KickOtherSession(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*SessionID_DTO, error) {
	out := new(SessionID_DTO)
	err := c.cc.Invoke(ctx, "/base.Auth/KickOtherSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Register(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/base.Auth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility
type AuthServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	Login(context.Context, *Credentials) (*SessionID_DTO, error)
	KickOtherSession(context.Context, *Credentials) (*SessionID_DTO, error)
	Register(context.Context, *Credentials) (*Empty, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (UnimplementedAuthServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuthServer) Login(context.Context, *Credentials) (*SessionID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServer) KickOtherSession(context.Context, *Credentials) (*SessionID_DTO, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickOtherSession not implemented")
}
func (UnimplementedAuthServer) Register(context.Context, *Credentials) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.Auth/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_KickOtherSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).KickOtherSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.Auth/KickOtherSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).KickOtherSession(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Auth_Ping_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "KickOtherSession",
			Handler:    _Auth_KickOtherSession_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
