name: tests
on:
  push:
  pull_request:

jobs:
  build:
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true

  lint:
    name: golangci-lint
    needs:
      -build
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

  unit:
    needs:
      -lint
    steps:
      - name: Test unit
        run: go test -tags=!integration -race -coverprofile unit.txt -covermode atomic ./...

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit.txt
          flags: unit
          name: unit

  integration:
    needs:
      -lint
    steps:
      - name: Test integration
        run: go test -tags=integration -race -coverprofile unit.txt -covermode atomic ./...

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit.txt
          flags: integration
          name: integration
